title:              Utpal's Blog
email:              cs14mtech11017@iith.ac.in
description:        Little from here, little from there!!
author:             Utpal Bora
#baseurl:            "/blog"
url:                "https://utpalbora.github.io"

# Social Profiles
twitter_username:   utpal4060
github_username:    utpalbora
facebook_username:  utpal4060
instagram_username:  
linkedin_username:  borautpal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
